const FONT_AVG_WIDTH_EM = 0.5;

const FONT_SIZE_LARGE = 1.875;
const FONT_SIZE_MEDIUM = 1.25;
const FONT_SIZE_SMALL = 1.125;
const SMALL_FONT_SIZE_LARGE = 1.5;
const SMALL_FONT_SIZE_MEDIUM = 1.125;
const SMALL_FONT_SIZE_SMALL = 1;

export const FONT_WIDTH_LARGE = FONT_SIZE_LARGE * FONT_AVG_WIDTH_EM; // 0.9375
export const FONT_WIDTH_MEDIUM = FONT_SIZE_MEDIUM * FONT_AVG_WIDTH_EM; // 0.625
export const FONT_WIDTH_SMALL = FONT_SIZE_SMALL * FONT_AVG_WIDTH_EM; // 0.5625

export const SMALL_FONT_WIDTH_LARGE = SMALL_FONT_SIZE_LARGE * FONT_AVG_WIDTH_EM; // 0.75
export const SMALL_FONT_WIDTH_MEDIUM = SMALL_FONT_SIZE_MEDIUM * FONT_AVG_WIDTH_EM; // 0.5625
export const SMALL_FONT_WIDTH_SMALL = SMALL_FONT_SIZE_SMALL * FONT_AVG_WIDTH_EM; // 0.5

export const ARROW_WIDTH_SMALL = 1.25;
export const ARROW_WIDTH_MEDIUM = 1.5;
export const ARROW_WIDTH_LARGE = 1.75;

export const PADDING_LEFT = 1;
export const PADDING_RIGHT = 0.375;
export const ARROW_MARGIN_RIGHT = 0.625;

export const MIN_DROPDOWN_WIDTH_SCALE = 0.965;
export const MAX_DROPDOWN_WIDTH_SCALE = 1.1;
