import { DEFAULT_BUTTON_SIZE } from "../Buttons/buttonConsts";

const MEDIUM_FONT_AVG_WIDTH_EM = 0.56;
const TEXT_SIZE = 0.875;
const APP_TAB_LABEL_LENGTH = 5;
const NUMBER_OF_TAB_BUTTONS = 3;

export const TAB_BUTTONS_CONTAINER_MARGIN_X = 0.125;

export const TAB_TEXT_WIDTH = TEXT_SIZE * MEDIUM_FONT_AVG_WIDTH_EM;
export const TAB_PADDING_LEFT = 0.65;
export const TAB_PADDING_RIGHT = 0.25;

export const TAB_CLOSE_BUTTON_SIZE = 1.5;
export const TAB_CLOSE_BUTTON_MARGIN_X = 0.125;

const LABEL_BUTTON_WIDTH =
    APP_TAB_LABEL_LENGTH * TAB_TEXT_WIDTH + (TAB_PADDING_LEFT + TAB_PADDING_RIGHT); // 3.35
const CLOSE_BUTTON_WIDTH = TAB_CLOSE_BUTTON_SIZE + TAB_CLOSE_BUTTON_MARGIN_X * 2; // 1.75

export const TAB_CONTAINER_WIDTH = LABEL_BUTTON_WIDTH + CLOSE_BUTTON_WIDTH; // 5.1
export const TAB_BUTTONS_CONTAINER_WIDTH =
    NUMBER_OF_TAB_BUTTONS * DEFAULT_BUTTON_SIZE + TAB_BUTTONS_CONTAINER_MARGIN_X * 2; // 7
